INSERT INTO products (
                      id,
                      brand,
                      clock_work,
                      description,
                      dial_color,
                      housing_material,
                      housing_thickness,
                      model,
                      name,
                      price,
                      strap_color,
                      strap_length,
                      strap_material,
                      use_for_description,
                      water_resistance,
                      year_of_issue)
VALUES (
        1,
        'Rolex',
        'Mechanically',
        'Gold watch with lots of diamonds and a gold dial.',
        'Gold',
        'Gold',
        '37mm',
        'Daytona',
        '"Diamond Lake"',
        '8350$',
        'Gold and white',
        '150mm',
        'High quality gold',
        'For important meetings',
        'Up to 3 atmospheres',
        '1968'
       );

INSERT INTO products (
    id,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           2,
           'Rolex',
           'Self-winding',
           'Rose gold and steel watch of the highest quality.',
           'Pink',
           'Pink gold',
           '29mm',
           'Daytona',
           '"Diamond Lake"',
           '8350$',
           'Pink and brown',
           '145mm',
           'Pink gold',
           'The best day to wear is the beginning of the week Monday.',
           'Up to 4 atmospheres',
           'Unknown'
       );

INSERT INTO products (
    id,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           3,
           'Rolex',
           'From the battery',
           'Low quality rose gold watch with stopwatch and timer waterproof.',
           'Light pink',
           'Rose gold',
           '45mm',
           'Daytona',
           '"Pink Monday"',
           '2860$',
           'Pink, black, brown',
           '160mm',
           'Low quality rose gold',
           'For everyday wear, scuba diving and important meetings.',
           'Up to 8 atmospheres',
           '1994'
       );