INSERT INTO users (id, email, first_name, last_name, password)
VALUES (1, 'mike@gmail.com', 'Misha', 'Pavliuk', 'Mike12345!');

INSERT INTO products (
                      id,
                      photo,
                      brand,
                      clock_work,
                      description,
                      dial_color,
                      housing_material,
                      housing_thickness,
                      model,
                      name,
                      price,
                      strap_color,
                      strap_length,
                      strap_material,
                      use_for_description,
                      water_resistance,
                      year_of_issue)
VALUES (
        1,
        'https://drive.google.com/uc?export=view&id=1OWHSNF6vfcJv7-bWipiFx5U_XcEJ3v77',
        'Rolex',
        'Mechanically',
        'Gold watch with lots of diamonds and a gold dial.',
        'Gold',
        'Gold',
        '37mm',
        'Daytona',
        '"Diamond Lake"',
        '8350',
        'Gold and white',
        '150mm',
        'High quality gold',
        'For important meetings.',
        'Up to 3 atmospheres',
        '1968'
       );

INSERT INTO products (
    id,
    photo,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           2,
           'https://drive.google.com/uc?export=view&id=1YIILanmVM1EGktyAyPF6ZbWS8DtJ6Waz',
           'Rolex',
           'Self-winding',
           'Rose gold and steel watch of the highest quality.',
           'Pink',
           'Pink gold',
           '29mm',
           'Daytona',
           '"Pink Monday"',
           '8350',
           'Pink and brown',
           '145mm',
           'Pink gold',
           'The best day to wear is the beginning of the week Monday.',
           'Up to 4 atmospheres',
           'Unknown'
       );

INSERT INTO products (
    id,
    photo,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           3,
           'https://drive.google.com/uc?export=view&id=15ZtNPBImvRCglBIqy1A4Rjke7kinXqPx',
           'Rolex',
           'From the battery',
           'Low quality rose gold watch with stopwatch and timer waterproof.',
           'Light pink',
           'Rose gold',
           '45mm',
           'Daytona',
           '"Chronograph Chocolate"',
           '2860',
           'Pink, black, brown',
           '160mm',
           'Low quality rose gold',
           'For everyday wear, scuba diving and important meetings.',
           'Up to 8 atmospheres',
           '1994'
       );

INSERT INTO products (
    id,
    photo,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           4,
           'https://drive.google.com/uc?export=view&id=1BTGJLjRaEU_nFAfNwNlWgIqIClai1ut4',
           'Patek Philippe',
           'Self-winding',
           'Watch with gold and crocodile leather bracelet.',
           'Light gold',
           'Gold-plated watch',
           '38mm',
           'Twent',
           '"Lunar crocodile"',
           '1620',
           'Black, brown',
           '142mm',
           'Crocodile skin',
           'For everyday wear, scuba diving and important meetings.',
           'Up to 8 atmospheres',
           '2003'
       );

INSERT INTO products (
    id,
    photo,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           5,
           'https://drive.google.com/uc?export=view&id=1Y-OJvNEqqxT3HJ39xaAANXzw8KIEKiiz',
           'Patek Philippe',
           'From the battery',
           'High quality silver with leather bracelet and steel clasps.',
           'Light silver',
           'Silver with steel latches',
           '49mm',
           'Geneve',
           '"Silver day"',
           '950',
           'Black',
           '162mm',
           'Leather bracelet',
           'For wearing to classic middle-class parties or walks.',
           'Up to 3 atmospheres',
           '2014'
       );

INSERT INTO products (
    id,
    photo,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           6,
           'https://drive.google.com/uc?export=view&id=1pqWrvWud5tBGNVntBDcZ0qa6_2rjnHWP',
           'Patek Philippe',
           'Mechanically',
           'The watch is made of a very old gold deposit.',
           'Gold',
           'Gold with impurities',
           '41mm',
           'Geneve',
           '"Ancient History"',
           '13570',
           'Brown, black',
           '156mm',
           'The skin of one of the oldest crocodiles',
           'For elegant parties and important business meetings.',
           'Up to 9 atmospheres',
           '1934'
       );

INSERT INTO products (
    id,
    photo,
    brand,
    clock_work,
    description,
    dial_color,
    housing_material,
    housing_thickness,
    model,
    name,
    price,
    strap_color,
    strap_length,
    strap_material,
    use_for_description,
    water_resistance,
    year_of_issue)
VALUES (
           7,
           'https://drive.google.com/uc?export=view&id=19Uk3gSrYpUZr0zK_rI2TRwxjx4ALtArf',
           'Atlantic',
           'From the battery',
           'The watch made of high quality materials is light, comfortable and suitable for scuba diving.',
           'Dark blue',
           'Anodized gold',
           '49mm',
           'Heart Ocean',
           '"Cold ocean"',
           '8240',
           'Dark blue, mat',
           '169mm',
           'Anodized silver bracelet',
           'Clock for shower and scuba diving.',
           'Up to 12 atmospheres',
           '1997'
       );
